//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hdSection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Company
    {
        public Company()
        {
            this.Games = new HashSet<Game>();
        }

        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string ContactPerson { get; set; }
        [Required]
        [RegularExpression(@".*@.*\..*", ErrorMessage = "Please input a valid email address.")]
        public string Email { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
