//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hdSection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Game
    {
        public Game()
        {
            this.Players = new HashSet<Player>();
        }
    
        [Required]
        public int No { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public int CompanyId { get; set; }
        [Required]
        public string Year { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
